name: PR
on:
  pull_request:
    branches:
      - main

jobs:
  checktitle:
    name: checktitle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2.5.4
        with:
        # You can specify specifying version range for the extra plugins if you prefer.
          semantic_version: 17
          # branches: |
          #   main
          extra_plugins: |
            semantic-release-pr-analyzer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}