name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action
        with:
          # semantic_version: 17
          extra_plugins: |
            @semantic-release/git
            @semantic-release/changelog
            @jortfal/semantic-release-terraform-config
          extends: |
            @jortfal/semantic-release-terraform-config
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}