name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2.5.4
        with:
          semantic_version: 17
          extra_plugins: |
            @semantic-release/git@9.0.1
            @semantic-release/exec@6.0.1
            @semantic-release/changelog@6.0.0
            @jortfal/semantic-release-terraform-config
          extends: |
            @jortfal/semantic-release-terraform-config
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}