name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2.5.4
        with:
        # You can specify specifying version range for the extra plugins if you prefer.
          semantic_version: 17
          branches: |
            main
          extra_plugins: |
            @semantic-release/changelog@5.0.1
            @semantic-release/git@9.0.0
            @jortfal/semantic-release-terraform-config@1.0.1
          extends: |
            @jortfal/semantic-release-terraform-config@1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
