name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2.5.4
        with:
        # You can specify specifying version range for the extra plugins if you prefer.
          branches: |
            main
          extra_plugins: |
            @jortfal/semantic-release-terraform-config
          extends: |
            @jortfal/semantic-release-terraform-config
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
